-- =============================================
-- Migration v47.0: e-Urząd Skarbowy (e-US) foundation
--
-- Module-toggleable integration with the Polish tax administration
-- e-Urząd Skarbowy (Bramka B = declarations like JPK_V7M, Bramka C =
-- KAS correspondence). This migration only adds schema + module
-- registration. No outbound calls until PR-2/PR-3 wire the services.
--
-- Master encryption key (eus_cert_encryption_key) is generated by
-- install.php on a fresh install or — if missing — at first call to
-- EusCertificateService::ensureKey(). Backup that key OFF-DISK before
-- production use; loss of the key = unrecoverable client certificates.
--
-- Bezpieczne do wielokrotnego uruchomienia.
-- =============================================

-- ── Register the module ──────────────────────────────────
-- NOT auto-enabled for existing offices (master admin must opt-in
-- per office via /admin/offices/{id}/modules — same pattern as
-- 'analytics' / 'hr' / 'sftp' / 'contracts' modules).
INSERT IGNORE INTO modules (name, slug, description, icon, category, is_system, sort_order)
VALUES (
    'e-Urząd Skarbowy',
    'eus',
    'Składanie JPK_V7 do urzędu i odbiór korespondencji z KAS przez bramki e-US',
    'fas fa-landmark',
    'integrations',
    0,
    60
);

-- ── Per-client configuration ─────────────────────────────
-- One row per client that uses e-US. office_id is denormalized as a
-- tenant guard so every query can filter by it without a JOIN.
CREATE TABLE IF NOT EXISTS client_eus_configs (
    id                              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id                       INT UNSIGNED NOT NULL,
    office_id                       INT UNSIGNED NOT NULL COMMENT 'tenant scope (denormalized for fast WHERE)',

    environment                     ENUM('mock','test','prod') NOT NULL DEFAULT 'mock',
    auth_method                     ENUM('cert_qual','profil_zaufany','mdowod') NOT NULL DEFAULT 'cert_qual',

    -- Qualified e-signature path (auth_method='cert_qual')
    cert_encrypted                  LONGBLOB DEFAULT NULL COMMENT 'AES-256-GCM ciphertext of PFX/P12',
    cert_passphrase_encrypted       VARBINARY(512) DEFAULT NULL COMMENT 'AES-256-GCM ciphertext of passphrase',
    cert_subject                    VARCHAR(255) DEFAULT NULL,
    cert_fingerprint                VARCHAR(128) DEFAULT NULL,
    cert_valid_from                 DATETIME DEFAULT NULL,
    cert_valid_to                   DATETIME DEFAULT NULL,

    -- Profil Zaufany / mDowód path (auth_method != cert_qual)
    auth_provider_token_encrypted   LONGBLOB DEFAULT NULL COMMENT 'AES-256-GCM ciphertext of SAML artifact / OAuth tokens',
    auth_provider_subject           VARCHAR(255) DEFAULT NULL,
    auth_provider_valid_to          DATETIME DEFAULT NULL,

    -- Pełnomocnictwo UPL-1 (power of attorney from client to office)
    upl1_status                     ENUM('none','pending','active','revoked','expired') NOT NULL DEFAULT 'none',
    upl1_valid_from                 DATE DEFAULT NULL,
    upl1_valid_to                   DATE DEFAULT NULL,
    upl1_scope                      SET('declarations','correspondence','full') DEFAULT NULL,
    upl1_pdf_path                   VARCHAR(500) DEFAULT NULL COMMENT 'relative path under storage/eus/upl1/',
    upl1_uploaded_at                DATETIME DEFAULT NULL,

    -- Bramki + polling
    bramka_b_enabled                TINYINT(1) NOT NULL DEFAULT 0,
    bramka_c_enabled                TINYINT(1) NOT NULL DEFAULT 0,
    auto_submit_eus                 TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'opt-in: chain submit to e-US after JPK generation',
    poll_incoming_enabled           TINYINT(1) NOT NULL DEFAULT 1,
    poll_interval_minutes           SMALLINT UNSIGNED NOT NULL DEFAULT 15,
    last_poll_at                    DATETIME DEFAULT NULL,

    created_at                      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY ux_client_eus (client_id),
    KEY ix_office (office_id),
    KEY ix_upl1_expiry (upl1_valid_to),
    KEY ix_cert_expiry (cert_valid_to),
    KEY ix_poll_due (poll_incoming_enabled, last_poll_at),

    CONSTRAINT fk_eus_cfg_client
        FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Canonical registry of all e-US documents ─────────────
-- One row per submission (Bramka B) and per incoming letter (Bramka C).
-- Surfacing layer (PR-3 / PR-4) writes message_id / task_id back here
-- so the message thread + e-US registry stay linked.
CREATE TABLE IF NOT EXISTS eus_documents (
    id                      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id               INT UNSIGNED NOT NULL,
    office_id               INT UNSIGNED NOT NULL COMMENT 'tenant scope',

    bramka                  ENUM('B','C') NOT NULL,
    direction               ENUM('out','in') NOT NULL,
    doc_kind                VARCHAR(40) NOT NULL COMMENT 'JPK_V7M | JPK_FA | KAS_letter | KAS_reply | ...',
    reference_no            VARCHAR(80) DEFAULT NULL COMMENT 'numer referencyjny e-US',

    payload_path            VARCHAR(500) DEFAULT NULL COMMENT 'XML/PDF in storage/eus/{client_id}/...',
    upo_path                VARCHAR(500) DEFAULT NULL COMMENT 'UPO XML/PDF when received',

    status                  ENUM('queued','signed','submitted','przyjety','zaakceptowany','odrzucony','received','replied','error') NOT NULL,
    status_message          TEXT DEFAULT NULL,

    related_period          CHAR(7) DEFAULT NULL COMMENT 'YYYY-MM for JPK',
    related_status_id       INT UNSIGNED DEFAULT NULL COMMENT 'informal FK to client_monthly_status.id',

    -- Surfacing FKs (filled by PR-3/PR-4)
    message_id              INT UNSIGNED DEFAULT NULL,
    task_id                 INT UNSIGNED DEFAULT NULL,

    external_received_at    DATETIME DEFAULT NULL COMMENT 'KAS-stamped receive time (incoming letters)',
    submitted_at            DATETIME DEFAULT NULL,
    finalized_at            DATETIME DEFAULT NULL,

    -- Retention: 10 years for KAS correspondence; NULL = no auto-purge.
    -- RodoDeleteService refuses to remove a client while retain_until > NOW().
    retain_until            DATE DEFAULT NULL,
    purged_at               DATETIME DEFAULT NULL COMMENT 'soft-purge tombstone marker',

    created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    KEY ix_client_dir       (client_id, direction, status),
    KEY ix_office           (office_id),
    KEY ix_reference        (reference_no),
    KEY ix_retain           (retain_until),
    KEY ix_message          (message_id),
    KEY ix_task             (task_id),

    CONSTRAINT fk_eus_doc_client
        FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Idempotency: one outbound submission per (client, doc_kind, period,
-- direction='out') can reach a non-rejected terminal state. Incoming
-- letters have related_period=NULL — MariaDB treats NULLs as distinct
-- in UNIQUE indexes so they never collide with this constraint.
-- Re-submission of the same period requires explicit deletion of the
-- previous row OR transitioning it to 'odrzucony' / 'error' (then
-- application-layer logic allows a new row).
CREATE UNIQUE INDEX ux_eus_outbound_period
    ON eus_documents (client_id, doc_kind, related_period, direction);

-- ── Audit log (separate from audit_log, no 37d retention) ──
CREATE TABLE IF NOT EXISTS eus_operations_log (
    id                  BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    document_id         INT UNSIGNED DEFAULT NULL,
    client_id           INT UNSIGNED DEFAULT NULL,
    user_id             INT UNSIGNED DEFAULT NULL COMMENT 'office | employee | system',
    user_type           VARCHAR(32) DEFAULT NULL,
    session_id          VARCHAR(64) DEFAULT NULL,
    operation           VARCHAR(64) NOT NULL,
    request_excerpt     TEXT DEFAULT NULL COMMENT 'masked, truncated to 4kB',
    response_excerpt    TEXT DEFAULT NULL,
    http_status         SMALLINT UNSIGNED DEFAULT NULL,
    duration_ms         INT UNSIGNED DEFAULT NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    KEY ix_doc          (document_id),
    KEY ix_session      (session_id),
    KEY ix_client       (client_id),
    KEY ix_created      (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Async job queue (twin of storage/ksef_send/{jobId}.json) ──
CREATE TABLE IF NOT EXISTS eus_jobs (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_uuid            CHAR(36) NOT NULL,
    client_id           INT UNSIGNED NOT NULL,
    document_id         INT UNSIGNED DEFAULT NULL,
    job_type            ENUM('submit_b','poll_b','poll_c','reply_c','renew_session') NOT NULL,
    state               ENUM('pending','running','done','failed') NOT NULL DEFAULT 'pending',
    attempts            SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    next_run_at         DATETIME DEFAULT NULL,
    payload_json        JSON DEFAULT NULL,
    result_json         JSON DEFAULT NULL,
    error_message       TEXT DEFAULT NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY ux_job_uuid      (job_uuid),
    KEY        ix_state_next    (state, next_run_at),
    KEY        ix_client_state  (client_id, state),
    KEY        ix_document      (document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Self-register migration ──────────────────────────────
INSERT IGNORE INTO schema_migrations (filename) VALUES
  ('migration_v47.0_eus_foundation.sql');
